//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTAIVSetupUtility.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTAIVSetupUtility.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU DXVK Support.
        /// </summary>
        public static string AboutdGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutdGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK to install.
        /// </summary>
        public static string AboutDXVKToInstall {
            get {
                return ResourceManager.GetString("AboutDXVKToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU DXVK Support.
        /// </summary>
        public static string AboutiGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutiGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is made by Gillian for the GTA IV Modding Guide. Below is internal information text which may be useful for debugging..
        /// </summary>
        public static string AboutIntroText {
            get {
                return ResourceManager.GetString("AboutIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have an outdated ASI Loader (dsound.dll). It&apos;s highly recommended to update it for best mod compatibility.\n\nDelete dsound.dll and press &apos;Yes&apos; to get redirected to download the latest version - download the non-x64 one, rename dinput8.dll to xlive.dll if you are using a downgraded version and don&apos;t plan to play GFWL..
        /// </summary>
        public static string ASILoaderOutdatedDescription {
            get {
                return ResourceManager.GetString("ASILoaderOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated ASI Loader.
        /// </summary>
        public static string ASILoaderOutdatedTitle {
            get {
                return ResourceManager.GetString("ASILoaderOutdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK-async is the next best alternative to stutter-less experience - since your GPU doesn&apos;t support GPL with Fast Linking, you can reduce stutter with async shader building, which will be a little faster than traditional shader building..
        /// </summary>
        public static string AsyncTipDescription {
            get {
                return ResourceManager.GetString("AsyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding async.
        /// </summary>
        public static string AsyncTipTitle {
            get {
                return ResourceManager.GetString("AsyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -availablevidmem.
        /// </summary>
        public static string AvailableVidMem {
            get {
                return ResourceManager.GetString("AvailableVidMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows to change between a 3GB and a 4GB VRAM lock when setting -availablevidmem up.\n\nThe game is 32-bit, so going beyond 4GB is entirely pointless. However, some people reported less issues with it being locked to 3GB instead.\n\nIt&apos;s recommended to keep this at default. Option is disabled if latest FusionFix is detected..
        /// </summary>
        public static string AvailableVidMemLockTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding the memory size locks.
        /// </summary>
        public static string AvailableVidMemLockTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option forces a specific value of video memory due to the game not being able to do so automatically sometimes. It&apos;s recommended to keep this at default..
        /// </summary>
        public static string AvailableVidMemTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -availablevidmem.
        /// </summary>
        public static string AvailableVidMemTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Windowed.
        /// </summary>
        public static string BorderlessWindowed {
            get {
                return ResourceManager.GetString("BorderlessWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Directory:.
        /// </summary>
        public static string DirectoryLabelSelected {
            get {
                return ResourceManager.GetString("DirectoryLabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your game directory before using:.
        /// </summary>
        public static string DirectoryLabelUnselected {
            get {
                return ResourceManager.GetString("DirectoryLabelUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been installed!\n\nConsider going to Steam - Settings - Downloads and disable `Enable Shader Pre-caching` - this may improve your performance.\n\nAdditionally, you can enable ReBAR and force it for the game - that may, too, improve performance..
        /// </summary>
        public static string DXVKInstalledDescription {
            get {
                return ResourceManager.GetString("DXVKInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK Installed!.
        /// </summary>
        public static string DXVKInstalledTitle {
            get {
                return ResourceManager.GetString("DXVKInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... ({0}%).
        /// </summary>
        public static string DXVKTextDownloading {
            get {
                return ResourceManager.GetString("DXVKTextDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall DXVK.
        /// </summary>
        public static string DXVKTextInstalled {
            get {
                return ResourceManager.GetString("DXVKTextInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string DXVKTextInstalling {
            get {
                return ResourceManager.GetString("DXVKTextInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install DXVK.
        /// </summary>
        public static string DXVKTextNotInstalled {
            get {
                return ResourceManager.GetString("DXVKTextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK with all it&apos;s remains successfully uninstalled..
        /// </summary>
        public static string DXVKUninstalledDescription {
            get {
                return ResourceManager.GetString("DXVKUninstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK uninstalled.
        /// </summary>
        public static string DXVKUninstalledTitle {
            get {
                return ResourceManager.GetString("DXVKUninstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable VSync.
        /// </summary>
        public static string EnableVSync {
            get {
                return ResourceManager.GetString("EnableVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app couldn&apos;t copy the options to clipboard - input them manually:\n\n{0}.
        /// </summary>
        public static string FailedToCopyDescription {
            get {
                return ResourceManager.GetString("FailedToCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy launch options.
        /// </summary>
        public static string FailedToCopyTitle {
            get {
                return ResourceManager.GetString("FailedToCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that your FusionFix is outdated. It is highly recommended to update the mod for access to latest stability improvements, fixes and graphical improvements\n\nPress &quot;Yes&quot; to be redirected to the download page for FusionFix..
        /// </summary>
        public static string FusionFixOutdatedDescription {
            get {
                return ResourceManager.GetString("FusionFixOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated FusionFix.
        /// </summary>
        public static string FusionFixOutdatedTitle {
            get {
                return ResourceManager.GetString("FusionFixOutdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to be using GFWL. Do you wish to remove Steam Achievements (if exists) and fix ZolikaPatch options to receive GFWL achievements?\n\nPressing &apos;No&apos; can revert this if you agreed to this earlier..
        /// </summary>
        public static string GFWLAchievementsDescription {
            get {
                return ResourceManager.GetString("GFWLAchievementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFWL Achievements.
        /// </summary>
        public static string GFWLAchievementsTitle {
            get {
                return ResourceManager.GetString("GFWLAchievementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit my Guide for more info and optimal graphics settings.
        /// </summary>
        public static string GuideLink {
            get {
                return ResourceManager.GetString("GuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the async patch.
        /// </summary>
        public static string InstallAsyncPatch {
            get {
                return ResourceManager.GetString("InstallAsyncPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install DXVK?.
        /// </summary>
        public static string InstallDXVKPrompt {
            get {
                return ResourceManager.GetString("InstallDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your iGPU supports DXVK but your GPU doesn&apos;t - do you still wish to install DXVK?.
        /// </summary>
        public static string InstallDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InstallDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK on Intel iGPUs.
        /// </summary>
        public static string InteliGPUDXVKPrompt {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC only has an Intel iGPU on it. While it does support more modern versions on paper, it&apos;s reported that DXVK 1.10.1 might be your only supported version. Do you wish to install it?\n\nIf &apos;No&apos; is selected, DXVK will be installed following the normal procedure..
        /// </summary>
        public static string InteliGPUDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder does not contain GTA IV..
        /// </summary>
        public static string InvalidFolderNoGTAIV {
            get {
                return ResourceManager.GetString("InvalidFolderNoGTAIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid folder.
        /// </summary>
        public static string InvalidFolderTitle {
            get {
                return ResourceManager.GetString("InvalidFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder contains GTAIV.exe, but it is not a version that this tool supports..
        /// </summary>
        public static string InvalidFolderWrongVersion {
            get {
                return ResourceManager.GetString("InvalidFolderWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputted value is invalid. Input again..
        /// </summary>
        public static string InvalidInputDescription {
            get {
                return ResourceManager.GetString("InvalidInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string InvalidInputTitle {
            get {
                return ResourceManager.GetString("InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option may help avoiding further framepacing issues. It&apos;s recommended to keep this on..
        /// </summary>
        public static string LatencyTipDescription {
            get {
                return ResourceManager.GetString("LatencyTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Max Frame Latency.
        /// </summary>
        public static string LatencyTipTitle {
            get {
                return ResourceManager.GetString("LatencyTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest {0}.
        /// </summary>
        public static string LatestText {
            get {
                return ResourceManager.GetString("LatestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following launch options have been set up automatically for you: \n\n{0}\n\nDo not worry that VRAM value isn&apos;t your full value - that is intentional and you can change that if you need to - however, there is no real reason to..
        /// </summary>
        public static string LaunchOptionsSetUpDescription {
            get {
                return ResourceManager.GetString("LaunchOptionsSetUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch options are set up!.
        /// </summary>
        public static string LaunchOptionsSetUpTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsSetUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app can&apos;t set the launch options automatically, paste them in Steam/RGL&apos;s Launch Options manually (will be copied to clipboard after you press Ok):\n\n{0}\n\nDo not worry that VRAM value isn&apos;t your full value - that is intentional and you can change that if you need to - however, there is no real reason to..
        /// </summary>
        public static string LaunchOptionsSteamDescription {
            get {
                return ResourceManager.GetString("LaunchOptionsSteamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about launch options on Steam/RGL.
        /// </summary>
        public static string LaunchOptionsSteamTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsSteamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK installation and Vulkan checking is only available on Windows.\n\nThese features have been disabled. Launch options configuration remains available..
        /// </summary>
        public static string LinuxDetectedDescription {
            get {
                return ResourceManager.GetString("LinuxDetectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux detected.
        /// </summary>
        public static string LinuxDetectedTitle {
            get {
                return ResourceManager.GetString("LinuxDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locked to:.
        /// </summary>
        public static string LockedTo {
            get {
                return ResourceManager.GetString("LockedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Details.
        /// </summary>
        public static string MonitorDetails {
            get {
                return ResourceManager.GetString("MonitorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option forces a specific resolution and refresh rate due to the game not being able to do so automatically sometimes. It&apos;s recommended to keep this at default..
        /// </summary>
        public static string MonitorDetailsTipDescription {
            get {
                return ResourceManager.GetString("MonitorDetailsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Monitor Details.
        /// </summary>
        public static string MonitorDetailsTipTitle {
            get {
                return ResourceManager.GetString("MonitorDetailsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -nomemrestrict.
        /// </summary>
        public static string NoMemRestrict {
            get {
                return ResourceManager.GetString("NoMemRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows the game to use all the dedicated memory resources up to the limits. It&apos;s recommended to keep this on..
        /// </summary>
        public static string NoMemRestrictTipDescription {
            get {
                return ResourceManager.GetString("NoMemRestrictTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -nomemrestrict.
        /// </summary>
        public static string NoMemRestrictTipTitle {
            get {
                return ResourceManager.GetString("NoMemRestrictTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -norestrictions.
        /// </summary>
        public static string NoRestrictions {
            get {
                return ResourceManager.GetString("NoRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to set any in-game settings independently of what the game restricts you to. It&apos;s recommended to keep this on..
        /// </summary>
        public static string NoRestrictionsTipDescription {
            get {
                return ResourceManager.GetString("NoRestrictionsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -norestrictions.
        /// </summary>
        public static string NoRestrictionsTipTitle {
            get {
                return ResourceManager.GetString("NoRestrictionsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nMake sure your drivers are up-to-date - don&apos;t rely on Windows Update drivers, either.
        ///.
        /// </summary>
        public static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string OpenSourceLink {
            get {
                return ResourceManager.GetString("OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have RivaTuner Statistics Server enabled (it might be a part of MSI Afterburner).\n\nTo avoid issues with the game launching when DXVK and IVSDK .NET are both installed, go into your tray icons, press on the little monitor icon with the number 60, press &apos;Add&apos; in bottom left, select GTA IV&apos;s executable and set Application detection level to &apos;None&apos;.\n\nIf you want the statistics, set it to Low and restart the tool, with the game running..
        /// </summary>
        public static string RTSSConflictDescription {
            get {
                return ResourceManager.GetString("RTSSConflictDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RivaTuner Conflict.
        /// </summary>
        public static string RTSSConflictTitle {
            get {
                return ResourceManager.GetString("RTSSConflictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing the GTAIV.exe.
        /// </summary>
        public static string SelectGTAIVFolder {
            get {
                return ResourceManager.GetString("SelectGTAIVFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Max Frame Latency.
        /// </summary>
        public static string SetMaxFrameLatency {
            get {
                return ResourceManager.GetString("SetMaxFrameLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup launch options.
        /// </summary>
        public static string SetupLaunchOptions {
            get {
                return ResourceManager.GetString("SetupLaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have a commandline.txt, however you are using the Steam/RGL version which doesn&apos;t use that file.\n\nConsider moving these options to Steam Launch Options or launch arguments..
        /// </summary>
        public static string SteamVersionNoticeDescription {
            get {
                return ResourceManager.GetString("SteamVersionNoticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Steam Version Notice&quot;.
        /// </summary>
        public static string SteamVersionNoticeTitle {
            get {
                return ResourceManager.GetString("SteamVersionNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present with conflicts.
        /// </summary>
        public static string SupportConflict {
            get {
                return ResourceManager.GetString("SupportConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full support with Fast Linking.
        /// </summary>
        public static string SupportFull {
            get {
                return ResourceManager.GetString("SupportFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to 1.10.1.
        /// </summary>
        public static string SupportIntel {
            get {
                return ResourceManager.GetString("SupportIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string SupportLatest {
            get {
                return ResourceManager.GetString("SupportLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy (pre-2.x).
        /// </summary>
        public static string SupportLegacy {
            get {
                return ResourceManager.GetString("SupportLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to 2.6.2.
        /// </summary>
        public static string SupportNewer {
            get {
                return ResourceManager.GetString("SupportNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SupportNone {
            get {
                return ResourceManager.GetString("SupportNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present, outdated.
        /// </summary>
        public static string SupportOutdated {
            get {
                return ResourceManager.GetString("SupportOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly supported, no Fast Linking.
        /// </summary>
        public static string SupportPartly {
            get {
                return ResourceManager.GetString("SupportPartly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string SupportPresent {
            get {
                return ResourceManager.GetString("SupportPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SupportUnknown {
            get {
                return ResourceManager.GetString("SupportUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the options at default values unless you know what you&apos;re doing..
        /// </summary>
        public static string TipsNote {
            get {
                return ResourceManager.GetString("TipsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gillian&apos;s GTA IV Setup Utility.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string UninstallDxvk {
            get {
                return ResourceManager.GetString("UninstallDxvk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3GB.
        /// </summary>
        public static string VidMemLimit3GB {
            get {
                return ResourceManager.GetString("VidMemLimit3GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4GB.
        /// </summary>
        public static string VidMemLimit4GB {
            get {
                return ResourceManager.GetString("VidMemLimit4GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect VRAM automatically.\n\nPlease enter your VRAM (in MB):.
        /// </summary>
        public static string VRAMManualDescription {
            get {
                return ResourceManager.GetString("VRAMManualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM check failed.
        /// </summary>
        public static string VRAMManualTitle {
            get {
                return ResourceManager.GetString("VRAMManualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in-game VSync implementation produces framepacing issues. DXVK&apos;s VSync implementation should be preferred.\n\nIt&apos;s recommended to keep this on and in-game&apos;s implementation off..
        /// </summary>
        public static string VSyncTipDescription {
            get {
                return ResourceManager.GetString("VSyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding VSync.
        /// </summary>
        public static string VSyncTipTitle {
            get {
                return ResourceManager.GetString("VSyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to your (likely main) discrete GPU being a 50-series NVIDIA GPU, make sure your drivers are up-to-date, as DXVK may not work on outdated drivers..
        /// </summary>
        public static string VulkanInfo50Series {
            get {
                return ResourceManager.GetString("VulkanInfo50Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vulkaninfo check failed for discrete GPU but succeeded for the integrated GPU. This usually means your discrete GPU does not support Vulkan.\n\nDXVK is available, but with the assumption that you&apos;re going to be playing off the integrated GPU, not the dedicated one..
        /// </summary>
        public static string VulkanInfoCheckFailDGPU {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFailDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vulkaninfo check failed entirely. This usually means none of your GPU&apos;s support Vulkan. Make sure your drivers are up-to-date - don&apos;t rely on Windows Update drivers, either.\n\nDXVK is not available..
        /// </summary>
        public static string VulkanInfoCheckFullFailDescription {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFullFailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vulkaninfo check failed entirely.
        /// </summary>
        public static string VulkanInfoCheckFullFailTitle {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFullFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vulkaninfo check failed for one of the GPUs but succeeded for the rest. This usually means one of your discrete GPUs does not support Vulkan.\n\nDXVK is available, but with the assumption that you&apos;re going to be playing off the supported GPU..
        /// </summary>
        public static string VulkanInfoCheckOneGPUFail {
            get {
                return ResourceManager.GetString("VulkanInfoCheckOneGPUFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vulkaninfo check failed partially. This usually means one of your GPU&apos;s may support Vulkan but have outdated drivers - the tool will proceed assuming so, but installing DXVK is not recommended..
        /// </summary>
        public static string VulkanInfoFailPartial {
            get {
                return ResourceManager.GetString("VulkanInfoFailPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GPL check failed for one of the GPUs but Fast Linking is supported by at least one of them. This usually means one of your discrete GPUs or the iGPU does not support DXVK in full.\n\nThe tool will proceed with the assumption that you&apos;re going to be playing off the GPU that didn&apos;t fail the GPL check (usually your main GPU), but provide options for async just incase..
        /// </summary>
        public static string VulkanInfoOneGPLFail {
            get {
                return ResourceManager.GetString("VulkanInfoOneGPLFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gillian&apos;s GTA IV Setup Utility!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which DXVK version to install?.
        /// </summary>
        public static string WhichDXVKPrompt {
            get {
                return ResourceManager.GetString("WhichDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your iGPU supports a greater version of DXVK than your GPU - which version do you wish to install?\n\nPress &apos;Yes&apos; to install the version matching your GPU.\n\nPress &apos;No&apos; to install the version matching your iGPU instead..
        /// </summary>
        public static string WhichDXVKPromptDescription {
            get {
                return ResourceManager.GetString("WhichDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows to use Borderless Fullscreen instead of Exclusive Fullscreen. Provides better experience and sometimes better performance. It&apos;s recommended to keep this on..
        /// </summary>
        public static string WindowedTipDescription {
            get {
                return ResourceManager.GetString("WindowedTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Borderless Windowed.
        /// </summary>
        public static string WindowedTipTitle {
            get {
                return ResourceManager.GetString("WindowedTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ZolikaPatch options are incompatible with FusionFix. This may lead to crashes, inconsistencies, visual issues etc.\n\nDo you wish to fix the options?.
        /// </summary>
        public static string ZPatchCompatibilityDescription {
            get {
                return ResourceManager.GetString("ZPatchCompatibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix ZolikaPatch - FusionFix compatibility?.
        /// </summary>
        public static string ZPatchCompatibilityTitle {
            get {
                return ResourceManager.GetString("ZPatchCompatibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZolikaPatch.ini has been modified to apply requested changes and fix any present issues with compatibility..
        /// </summary>
        public static string ZPatchIniModifiedDescription {
            get {
                return ResourceManager.GetString("ZPatchIniModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZolikaPatch.ini modified.
        /// </summary>
        public static string ZPatchIniModifiedTitle {
            get {
                return ResourceManager.GetString("ZPatchIniModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ZolikaPatch is outdated.\n\nDo you wish to download the latest version? (this will redirect to Zolika1351&apos;s website for manual download)
        ///.
        /// </summary>
        public static string ZPatchOutdatedDescription {
            get {
                return ResourceManager.GetString("ZPatchOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK to restart the app after updating ZolikaPatch. Do not unpack &apos;PlayGTAIV.exe&apos;..
        /// </summary>
        public static string ZPatchOutdatedDescription2 {
            get {
                return ResourceManager.GetString("ZPatchOutdatedDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZolikaPatch is outdated.
        /// </summary>
        public static string ZPatchOutdatedTitle {
            get {
                return ResourceManager.GetString("ZPatchOutdatedTitle", resourceCulture);
            }
        }
    }
}
