//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTAIVSetupUtility.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTAIVSetupUtility.Localizations.Resources.ru-RU", typeof(Resources_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка DXVK (дискретная).
        /// </summary>
        public static string AboutdGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutdGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия DXVK для установки.
        /// </summary>
        public static string AboutDXVKToInstall {
            get {
                return ResourceManager.GetString("AboutDXVKToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка DXVK (встроенная).
        /// </summary>
        public static string AboutiGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutiGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это ПО создано Gillian для руководства по моддингу GTA IV. Ниже приведена внутренняя информация, которая может быть полезна для отладки..
        /// </summary>
        public static string AboutIntroText {
            get {
                return ResourceManager.GetString("AboutIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, у вас устаревший ASI Loader (dsound.dll). Настоятельно рекомендуется обновить его для лучшей совместимости модов.\n\nУдалите dsound.dll и нажмите «Да», чтобы перейти к загрузке последней версии - скачайте версию без x64, переименуйте dinput8.dll в xlive.dll, если используете даунгрейд и не планируете играть в GFWL..
        /// </summary>
        public static string ASILoaderOutdatedDescription {
            get {
                return ResourceManager.GetString("ASILoaderOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устаревший ASI Loader.
        /// </summary>
        public static string ASILoaderOutdatedTitle {
            get {
                return ResourceManager.GetString("ASILoaderOutdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK-async — лучшая альтернатива для игры без фризов. Так как ваша видеокарта не поддерживает GPL с Fast Linking, вы можете уменьшить статтеры с помощью асинхронной компиляции шейдеров, что будет немного быстрее традиционного метода..
        /// </summary>
        public static string AsyncTipDescription {
            get {
                return ResourceManager.GetString("AsyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт async.
        /// </summary>
        public static string AsyncTipTitle {
            get {
                return ResourceManager.GetString("AsyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -availablevidmem.
        /// </summary>
        public static string AvailableVidMem {
            get {
                return ResourceManager.GetString("AvailableVidMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция позволяет переключаться между ограничением в 3ГБ и 4ГБ видеопамяти при настройке -availablevidmem.\n\nИгра 32-битная, поэтому идти выше 4ГБ бессмысленно. Однако некоторые пользователи сообщали о меньшем количестве проблем при блокировке до 3ГБ.\n\nРекомендуется оставить по умолчанию. Опция отключена, если обнаружен последний FusionFix..
        /// </summary>
        public static string AvailableVidMemLockTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт ограничений объема памяти.
        /// </summary>
        public static string AvailableVidMemLockTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция принудительно задает значение видеопамяти, так как игра иногда не может определить его автоматически. Рекомендуется оставить значение по умолчанию..
        /// </summary>
        public static string AvailableVidMemTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт -availablevidmem.
        /// </summary>
        public static string AvailableVidMemTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно без границ.
        /// </summary>
        public static string BorderlessWindowed {
            get {
                return ResourceManager.GetString("BorderlessWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с игрой:.
        /// </summary>
        public static string DirectoryLabelSelected {
            get {
                return ResourceManager.GetString("DirectoryLabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите папку с игрой перед использованием:.
        /// </summary>
        public static string DirectoryLabelUnselected {
            get {
                return ResourceManager.GetString("DirectoryLabelUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} был установлен!\n\nРекомендуется зайти в Steam -&gt; Настройки -&gt; Загрузки и отключить «Кэширование шейдеров» (Enable Shader Pre-caching) — это может улучшить производительность.\n\nКроме того, вы можете включить ReBAR и принудительно активировать его для игры — это тоже может повысить производительность..
        /// </summary>
        public static string DXVKInstalledDescription {
            get {
                return ResourceManager.GetString("DXVKInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK установлен!.
        /// </summary>
        public static string DXVKInstalledTitle {
            get {
                return ResourceManager.GetString("DXVKInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачивание... ({0}%).
        /// </summary>
        public static string DXVKTextDownloading {
            get {
                return ResourceManager.GetString("DXVKTextDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переуст. DXVK.
        /// </summary>
        public static string DXVKTextInstalled {
            get {
                return ResourceManager.GetString("DXVKTextInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка....
        /// </summary>
        public static string DXVKTextInstalling {
            get {
                return ResourceManager.GetString("DXVKTextInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить DXVK.
        /// </summary>
        public static string DXVKTextNotInstalled {
            get {
                return ResourceManager.GetString("DXVKTextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK и все его остатки успешно удалены..
        /// </summary>
        public static string DXVKUninstalledDescription {
            get {
                return ResourceManager.GetString("DXVKUninstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK удален.
        /// </summary>
        public static string DXVKUninstalledTitle {
            get {
                return ResourceManager.GetString("DXVKUninstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить VSync.
        /// </summary>
        public static string EnableVSync {
            get {
                return ResourceManager.GetString("EnableVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение не смогло скопировать параметры в буфер обмена — введите их вручную:\n\n{0}.
        /// </summary>
        public static string FailedToCopyDescription {
            get {
                return ResourceManager.GetString("FailedToCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось скопировать параметры запуска.
        /// </summary>
        public static string FailedToCopyTitle {
            get {
                return ResourceManager.GetString("FailedToCopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратите внимание, что у вас устаревший FusionFix. Настоятельно рекомендуется обновить мод для последних улучшений стабильности, исправлений и графических улучшений.\n\nНажмите «Да», чтобы перейти на страницу загрузки FusionFix..
        /// </summary>
        public static string FusionFixOutdatedDescription {
            get {
                return ResourceManager.GetString("FusionFixOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устаревший FusionFix.
        /// </summary>
        public static string FusionFixOutdatedTitle {
            get {
                return ResourceManager.GetString("FusionFixOutdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, вы используете GFWL. Хотите удалить Steam Achievements (если есть) и исправить настройки ZolikaPatch для получения достижений GFWL?\n\nНажатие «Нет» может отменить это действие, если вы согласились на него ранее..
        /// </summary>
        public static string GFWLAchievementsDescription {
            get {
                return ResourceManager.GetString("GFWLAchievementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достижения GFWL.
        /// </summary>
        public static string GFWLAchievementsTitle {
            get {
                return ResourceManager.GetString("GFWLAchievementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мое руководство для инфы и оптимальных настроек графики.
        /// </summary>
        public static string GuideLink {
            get {
                return ResourceManager.GetString("GuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить async патч.
        /// </summary>
        public static string InstallAsyncPatch {
            get {
                return ResourceManager.GetString("InstallAsyncPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить DXVK?.
        /// </summary>
        public static string InstallDXVKPrompt {
            get {
                return ResourceManager.GetString("InstallDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша встроенная графика поддерживает DXVK, но дискретная видеокарта — нет. Вы все равно хотите установить DXVK?.
        /// </summary>
        public static string InstallDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InstallDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK на Intel iGPUs.
        /// </summary>
        public static string InteliGPUDXVKPrompt {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш ПК имеет только встроенную графику Intel. Хотя на бумаге она поддерживает более новые версии, некоторые говорят, что DXVK 1.10.1 может быть единственной поддерживаемой версией. Хотите установить её?\n\nЕсли выберете «Нет», DXVK будет установлен по стандартной процедуре..
        /// </summary>
        public static string InteliGPUDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выбранной папке нет GTA IV..
        /// </summary>
        public static string InvalidFolderNoGTAIV {
            get {
                return ResourceManager.GetString("InvalidFolderNoGTAIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная папка.
        /// </summary>
        public static string InvalidFolderTitle {
            get {
                return ResourceManager.GetString("InvalidFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выбранной папке есть GTAIV.exe, но эта версия не поддерживается програмой..
        /// </summary>
        public static string InvalidFolderWrongVersion {
            get {
                return ResourceManager.GetString("InvalidFolderWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенное значение неверно. Введите снова..
        /// </summary>
        public static string InvalidInputDescription {
            get {
                return ResourceManager.GetString("InvalidInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ввод.
        /// </summary>
        public static string InvalidInputTitle {
            get {
                return ResourceManager.GetString("InvalidInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция может помочь избежать дополнительных проблем с плавностью. Рекомендуется оставить включенной..
        /// </summary>
        public static string LatencyTipDescription {
            get {
                return ResourceManager.GetString("LatencyTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт Max Frame Latency.
        /// </summary>
        public static string LatencyTipTitle {
            get {
                return ResourceManager.GetString("LatencyTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний {0}.
        /// </summary>
        public static string LatestText {
            get {
                return ResourceManager.GetString("LatestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующие параметры запуска были настроены автоматически:\n\n{0}\n\nНе беспокойтесь, что значение видеопамяти не соответствует вашему полному объему - так и задумано, вы можете изменить его при необходимости, но реальной причины для этого нет..
        /// </summary>
        public static string LaunchOptionsSetUpDescription {
            get {
                return ResourceManager.GetString("LaunchOptionsSetUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры запуска настроены!.
        /// </summary>
        public static string LaunchOptionsSetUpTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsSetUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа не может установить параметры запуска автоматически. Вставьте их в параметры запуска Steam/RGL вручную (они будут скопированы в буфер обмена после нажатия ОК):\n\n{0}\n\nНе беспокойтесь, что значение видеопамяти не соответствует вашему полному объему - так и задумано, вы можете изменить его при необходимости, но реальной причины для этого нет..
        /// </summary>
        public static string LaunchOptionsSteamDescription {
            get {
                return ResourceManager.GetString("LaunchOptionsSteamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о параметрах запуска в Steam/RGL.
        /// </summary>
        public static string LaunchOptionsSteamTitle {
            get {
                return ResourceManager.GetString("LaunchOptionsSteamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка DXVK и проверка Vulkan доступны только в Windows.\n\nЭти функции были отключены. Настройка параметров запуска остается доступной..
        /// </summary>
        public static string LinuxDetectedDescription {
            get {
                return ResourceManager.GetString("LinuxDetectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружен Linux.
        /// </summary>
        public static string LinuxDetectedTitle {
            get {
                return ResourceManager.GetString("LinuxDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до:.
        /// </summary>
        public static string LockedTo {
            get {
                return ResourceManager.GetString("LockedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о мониторе.
        /// </summary>
        public static string MonitorDetails {
            get {
                return ResourceManager.GetString("MonitorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция принудительно задает разрешение и частоту обновления, так как игра иногда не может сделать это автоматически. Рекомендуется оставить по умолчанию..
        /// </summary>
        public static string MonitorDetailsTipDescription {
            get {
                return ResourceManager.GetString("MonitorDetailsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт сведений о мониторе.
        /// </summary>
        public static string MonitorDetailsTipTitle {
            get {
                return ResourceManager.GetString("MonitorDetailsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -nomemrestrict.
        /// </summary>
        public static string NoMemRestrict {
            get {
                return ResourceManager.GetString("NoMemRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция позволяет игре использовать всю выделенную память до предела. Рекомендуется оставить включенной..
        /// </summary>
        public static string NoMemRestrictTipDescription {
            get {
                return ResourceManager.GetString("NoMemRestrictTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт -nomemrestrict.
        /// </summary>
        public static string NoMemRestrictTipTitle {
            get {
                return ResourceManager.GetString("NoMemRestrictTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -norestrictions.
        /// </summary>
        public static string NoRestrictions {
            get {
                return ResourceManager.GetString("NoRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция позволяет выставлять любые настройки в игре независимо от ограничений, накладываемых игрой. Рекомендуется оставить включенной..
        /// </summary>
        public static string NoRestrictionsTipDescription {
            get {
                return ResourceManager.GetString("NoRestrictionsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт -norestrictions.
        /// </summary>
        public static string NoRestrictionsTipTitle {
            get {
                return ResourceManager.GetString("NoRestrictionsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nУбедитесь, что ваши драйверы обновлены - также не полагайтесь на драйверы Windows Update..
        /// </summary>
        public static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть....
        /// </summary>
        public static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный код.
        /// </summary>
        public static string OpenSourceLink {
            get {
                return ResourceManager.GetString("OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данный момент у вас включен RivaTuner Statistics Server (возможно, как часть MSI Afterburner).\n\nЧтобы избежать проблем с запуском игры при одновременной установке DXVK и IVSDK .NET, зайдите в трей, нажмите на значок монитора с числом 60, нажмите «Add» внизу слева, выберите исполняемый файл GTA IV и установите «Application detection level» на «None».\n\nЕсли вам нужна статистика, установите значение на «Low» и перезапустите утилиту при запущенной игре..
        /// </summary>
        public static string RTSSConflictDescription {
            get {
                return ResourceManager.GetString("RTSSConflictDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфликт с RivaTuner.
        /// </summary>
        public static string RTSSConflictTitle {
            get {
                return ResourceManager.GetString("RTSSConflictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите папку, содержащую GTAIV.exe.
        /// </summary>
        public static string SelectGTAIVFolder {
            get {
                return ResourceManager.GetString("SelectGTAIVFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уст. Max Frame Latency.
        /// </summary>
        public static string SetMaxFrameLatency {
            get {
                return ResourceManager.GetString("SetMaxFrameLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить параметры запуска.
        /// </summary>
        public static string SetupLaunchOptions {
            get {
                return ResourceManager.GetString("SetupLaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, у вас есть файл commandline.txt, однако вы используете версию Steam/RGL, которая этот файл не использует.\n\nПеренесите эти параметры в параметры запуска Steam (Launch Options) или аргументы запуска..
        /// </summary>
        public static string SteamVersionNoticeDescription {
            get {
                return ResourceManager.GetString("SteamVersionNoticeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление для Steam-версии.
        /// </summary>
        public static string SteamVersionNoticeTitle {
            get {
                return ResourceManager.GetString("SteamVersionNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присутствует с конфликтом.
        /// </summary>
        public static string SupportConflict {
            get {
                return ResourceManager.GetString("SupportConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полная поддержка с Fast Linking.
        /// </summary>
        public static string SupportFull {
            get {
                return ResourceManager.GetString("SupportFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зафиксирована на 1.10.1.
        /// </summary>
        public static string SupportIntel {
            get {
                return ResourceManager.GetString("SupportIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя.
        /// </summary>
        public static string SupportLatest {
            get {
                return ResourceManager.GetString("SupportLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устаревшая (до 2.x).
        /// </summary>
        public static string SupportLegacy {
            get {
                return ResourceManager.GetString("SupportLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зафиксирована на 2.6.2.
        /// </summary>
        public static string SupportNewer {
            get {
                return ResourceManager.GetString("SupportNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string SupportNone {
            get {
                return ResourceManager.GetString("SupportNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присутствует, устарела.
        /// </summary>
        public static string SupportOutdated {
            get {
                return ResourceManager.GetString("SupportOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частичная поддержка, нет Fast Linking.
        /// </summary>
        public static string SupportPartly {
            get {
                return ResourceManager.GetString("SupportPartly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присутствует.
        /// </summary>
        public static string SupportPresent {
            get {
                return ResourceManager.GetString("SupportPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        public static string SupportUnknown {
            get {
                return ResourceManager.GetString("SupportUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подсказки.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не трогайте настройки, если не уверены в том, что делаете..
        /// </summary>
        public static string TipsNote {
            get {
                return ResourceManager.GetString("TipsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gillian&apos;s GTA IV Setup Utility.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string UninstallDxvk {
            get {
                return ResourceManager.GetString("UninstallDxvk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ГБ.
        /// </summary>
        public static string VidMemLimit3GB {
            get {
                return ResourceManager.GetString("VidMemLimit3GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ГБ.
        /// </summary>
        public static string VidMemLimit4GB {
            get {
                return ResourceManager.GetString("VidMemLimit4GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить видеопамять автоматически.\n\nПожалуйста, введите объем вашей видеопамяти (в МБ):.
        /// </summary>
        public static string VRAMManualDescription {
            get {
                return ResourceManager.GetString("VRAMManualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение видеопамяти не удалось.
        /// </summary>
        public static string VRAMManualTitle {
            get {
                return ResourceManager.GetString("VRAMManualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутриигровая вертикальная синхронизация (VSync) вызывает проблемы с плавностью. Лучше использовать реализацию VSync от DXVK.\n\nРекомендуется включить эту опцию, а внутриигровую — выключить..
        /// </summary>
        public static string VSyncTipDescription {
            get {
                return ResourceManager.GetString("VSyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт VSync.
        /// </summary>
        public static string VSyncTipTitle {
            get {
                return ResourceManager.GetString("VSyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поскольку ваша (вероятно, основная) дискретная видеокарта относится к серии NVIDIA 50хх, убедитесь, что драйверы обновлены, так как DXVK может не работать на устаревших драйверах..
        /// </summary>
        public static string VulkanInfo50Series {
            get {
                return ResourceManager.GetString("VulkanInfo50Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка vulkaninfo не прошла для дискретной видеокарты, но прошла для встроенной. Обычно это означает, что дискретная карта не поддерживает Vulkan.\n\nDXVK доступен, но с расчетом на то, что вы будете играть на встроенной графике, а не на дискретной..
        /// </summary>
        public static string VulkanInfoCheckFailDGPU {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFailDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка vulkaninfo полностью провалилась. Обычно это означает, что ни одна из ваших видеокарт не поддерживает Vulkan. Убедитесь, что драйверы обновлены (не полагайтесь на драйверы Windows Update).\n\nDXVK недоступен..
        /// </summary>
        public static string VulkanInfoCheckFullFailDescription {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFullFailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный сбой проверки vulkaninfo.
        /// </summary>
        public static string VulkanInfoCheckFullFailTitle {
            get {
                return ResourceManager.GetString("VulkanInfoCheckFullFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка vulkaninfo не прошла для одной из видеокарт, но прошла для остальных. Обычно это означает, что одна из ваших дискретных карт не поддерживает Vulkan.\n\nDXVK доступен, но с расчетом на то, что вы будете играть на поддерживаемой видеокарте..
        /// </summary>
        public static string VulkanInfoCheckOneGPUFail {
            get {
                return ResourceManager.GetString("VulkanInfoCheckOneGPUFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка vulkaninfo прошла частично. Обычно это означает, что одна из ваших видеокарт поддерживает Vulkan, но драйверы устарели. Утилита продолжит работу, предполагая это, но установка DXVK не рекомендуется..
        /// </summary>
        public static string VulkanInfoFailPartial {
            get {
                return ResourceManager.GetString("VulkanInfoFailPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка GPL не прошла для одного из графических процессоров, но Fast Linking поддерживается по крайней мере одним из них. Обычно это означает, что одна из ваших видеокарт не поддерживает DXVK в полном объеме. Программа продолжит работать, исходя из предположения, что вы будете играть на видеокарте, которая прошла проверку GPL (обычно это основная), но на всякий случай предоставит настройку для установки async..
        /// </summary>
        public static string VulkanInfoOneGPLFail {
            get {
                return ResourceManager.GetString("VulkanInfoOneGPLFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравия в Gillian&apos;s GTA IV Setup Utility!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какую версию DXVK установить?.
        /// </summary>
        public static string WhichDXVKPrompt {
            get {
                return ResourceManager.GetString("WhichDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша встроенная видеокарта поддерживает более новую версию DXVK, чем ваша дискретная — какую версию вы хотите установить?\n\nНажмите «Да», чтобы установить версию, соответствующую вашей дискретной видеокарте.\n\nНажмите «Нет», чтобы установить версию, соответствующую вашей встроенной видеокарте..
        /// </summary>
        public static string WhichDXVKPromptDescription {
            get {
                return ResourceManager.GetString("WhichDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта опция позволяет использовать полноэкранный оконный режим без границ вместо эксклюзивного полноэкранного режима. Обеспечивает более приятное использование ПК и иногда улучшенную производительность. Рекомендуется оставить эту опцию включенной..
        /// </summary>
        public static string WindowedTipDescription {
            get {
                return ResourceManager.GetString("WindowedTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На счёт окна без границ.
        /// </summary>
        public static string WindowedTipTitle {
            get {
                return ResourceManager.GetString("WindowedTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши настройки ZolikaPatch несовместимы с FusionFix. Это может привести к вылетам, несоответствиям, визуальным проблемам и т. д.\n\nВы хотите исправить настройки?.
        /// </summary>
        public static string ZPatchCompatibilityDescription {
            get {
                return ResourceManager.GetString("ZPatchCompatibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправить совместимость ZolikaPatch - FusionFix?.
        /// </summary>
        public static string ZPatchCompatibilityTitle {
            get {
                return ResourceManager.GetString("ZPatchCompatibilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл ZolikaPatch.ini был изменен, чтобы внести запрошенные изменения и исправить все существующие проблемы с совместимостью..
        /// </summary>
        public static string ZPatchIniModifiedDescription {
            get {
                return ResourceManager.GetString("ZPatchIniModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZolikaPatch.ini был изменен.
        /// </summary>
        public static string ZPatchIniModifiedTitle {
            get {
                return ResourceManager.GetString("ZPatchIniModifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш ZolikaPatch устарел.\n\nХотите скачать последнюю версию? (вы будете перенаправлены на сайт Zolika1351 для ручной загрузки).
        /// </summary>
        public static string ZPatchOutdatedDescription {
            get {
                return ResourceManager.GetString("ZPatchOutdatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите ОК, чтобы перезапустить приложение после обновления ZolikaPatch. Не распаковывайте «PlayGTAIV.exe»..
        /// </summary>
        public static string ZPatchOutdatedDescription2 {
            get {
                return ResourceManager.GetString("ZPatchOutdatedDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZolikaPatch устаревший.
        /// </summary>
        public static string ZPatchOutdatedTitle {
            get {
                return ResourceManager.GetString("ZPatchOutdatedTitle", resourceCulture);
            }
        }
    }
}
