//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTAIVSetupUtility.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTAIVSetupUtility.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU DXVK Support.
        /// </summary>
        public static string AboutdGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutdGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK to install.
        /// </summary>
        public static string AboutDXVKToInstall {
            get {
                return ResourceManager.GetString("AboutDXVKToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU DXVK Support.
        /// </summary>
        public static string AboutiGPUDXVKSupport {
            get {
                return ResourceManager.GetString("AboutiGPUDXVKSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is made by Gillian for the Modding Guide. Below is internal information text which may be useful for debugging..
        /// </summary>
        public static string AboutIntroText {
            get {
                return ResourceManager.GetString("AboutIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK-async is the next best alternative to stutter-less experience - since your GPU doesn&apos;t support GPL with Fast Linking, you can reduce stutter with async shader building, which will be a little faster than traditional shader building..
        /// </summary>
        public static string AsyncTipDescription {
            get {
                return ResourceManager.GetString("AsyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding async.
        /// </summary>
        public static string AsyncTipTitle {
            get {
                return ResourceManager.GetString("AsyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -availablevidmem.
        /// </summary>
        public static string AvailableVidMem {
            get {
                return ResourceManager.GetString("AvailableVidMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows to change between a 3GB and a 4GB VRAM lock when setting -availablevidmem up.\n\nThe game is 32-bit, so going beyond 4GB is entirely pointless. However, some people reported less issues with it being locked to 3GB instead.\n\nIt&apos;s recommended to keep this at default. Option is disabled if latest FusionFix is detected..
        /// </summary>
        public static string AvailableVidMemLockTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding the memory size locks.
        /// </summary>
        public static string AvailableVidMemLockTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemLockTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -availablevidmem.
        /// </summary>
        public static string AvailableVidMemTipDescription {
            get {
                return ResourceManager.GetString("AvailableVidMemTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option forces a specific value of video memory due to the game not being able to do so automatically sometimes. It&apos;s recommended to keep this at default..
        /// </summary>
        public static string AvailableVidMemTipTitle {
            get {
                return ResourceManager.GetString("AvailableVidMemTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Windowed.
        /// </summary>
        public static string BorderlessWindowed {
            get {
                return ResourceManager.GetString("BorderlessWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Directory:.
        /// </summary>
        public static string DirectoryLabelSelected {
            get {
                return ResourceManager.GetString("DirectoryLabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your game directory before using:.
        /// </summary>
        public static string DirectoryLabelUnselected {
            get {
                return ResourceManager.GetString("DirectoryLabelUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... ({0}%).
        /// </summary>
        public static string DXVKTextDownloading {
            get {
                return ResourceManager.GetString("DXVKTextDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall DXVK.
        /// </summary>
        public static string DXVKTextInstalled {
            get {
                return ResourceManager.GetString("DXVKTextInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string DXVKTextInstalling {
            get {
                return ResourceManager.GetString("DXVKTextInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install DXVK.
        /// </summary>
        public static string DXVKTextNotInstalled {
            get {
                return ResourceManager.GetString("DXVKTextNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable VSync.
        /// </summary>
        public static string EnableVSync {
            get {
                return ResourceManager.GetString("EnableVSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit my Guide for more info and optimal graphics settings.
        /// </summary>
        public static string GuideLink {
            get {
                return ResourceManager.GetString("GuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the async patch.
        /// </summary>
        public static string InstallAsyncPatch {
            get {
                return ResourceManager.GetString("InstallAsyncPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install DXVK?.
        /// </summary>
        public static string InstallDXVKPrompt {
            get {
                return ResourceManager.GetString("InstallDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your iGPU supports DXVK but your GPU doesn&apos;t - do you still wish to install DXVK?.
        /// </summary>
        public static string InstallDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InstallDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXVK on Intel iGPUs.
        /// </summary>
        public static string InteliGPUDXVKPrompt {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC only has an Intel iGPU on it. While it does support more modern versions on paper, it&apos;s reported that DXVK 1.10.1 might be your only supported version. Do you wish to install it?\n\nIf &apos;No&apos; is selected, DXVK will be installed following the normal procedure..
        /// </summary>
        public static string InteliGPUDXVKPromptDescription {
            get {
                return ResourceManager.GetString("InteliGPUDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option may help avoiding further framepacing issues. It&apos;s recommended to keep this on..
        /// </summary>
        public static string LatencyTipDescription {
            get {
                return ResourceManager.GetString("LatencyTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Max Frame Latency.
        /// </summary>
        public static string LatencyTipTitle {
            get {
                return ResourceManager.GetString("LatencyTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locked to:.
        /// </summary>
        public static string LockedTo {
            get {
                return ResourceManager.GetString("LockedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Details.
        /// </summary>
        public static string MonitorDetails {
            get {
                return ResourceManager.GetString("MonitorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option forces a specific resolution and refresh rate due to the game not being able to do so automatically sometimes. It&apos;s recommended to keep this at default..
        /// </summary>
        public static string MonitorDetailsTipDescription {
            get {
                return ResourceManager.GetString("MonitorDetailsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Monitor Details.
        /// </summary>
        public static string MonitorDetailsTipTitle {
            get {
                return ResourceManager.GetString("MonitorDetailsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -nomemrestrict.
        /// </summary>
        public static string NoMemRestrict {
            get {
                return ResourceManager.GetString("NoMemRestrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows the game to use all the dedicated memory resources up to the limits. It&apos;s recommended to keep this on..
        /// </summary>
        public static string NoMemRestrictTipDescription {
            get {
                return ResourceManager.GetString("NoMemRestrictTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -nomemrestrict.
        /// </summary>
        public static string NoMemRestrictTipTitle {
            get {
                return ResourceManager.GetString("NoMemRestrictTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -norestrictions.
        /// </summary>
        public static string NoRestrictions {
            get {
                return ResourceManager.GetString("NoRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows you to set any in-game settings independently of what the game restricts you to. It&apos;s recommended to keep this on..
        /// </summary>
        public static string NoRestrictionsTipDescription {
            get {
                return ResourceManager.GetString("NoRestrictionsTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding -norestrictions.
        /// </summary>
        public static string NoRestrictionsTipTitle {
            get {
                return ResourceManager.GetString("NoRestrictionsTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is open source.
        /// </summary>
        public static string OpenSourceLink {
            get {
                return ResourceManager.GetString("OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Max Frame Latency.
        /// </summary>
        public static string SetMaxFrameLatency {
            get {
                return ResourceManager.GetString("SetMaxFrameLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup launch options.
        /// </summary>
        public static string SetupLaunchOptions {
            get {
                return ResourceManager.GetString("SetupLaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full support with Fast Linking.
        /// </summary>
        public static string SupportFull {
            get {
                return ResourceManager.GetString("SupportFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to 1.10.1.
        /// </summary>
        public static string SupportIntel {
            get {
                return ResourceManager.GetString("SupportIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string SupportLatest {
            get {
                return ResourceManager.GetString("SupportLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy (pre-2.x).
        /// </summary>
        public static string SupportLegacy {
            get {
                return ResourceManager.GetString("SupportLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked to 2.6.2.
        /// </summary>
        public static string SupportNewer {
            get {
                return ResourceManager.GetString("SupportNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SupportNone {
            get {
                return ResourceManager.GetString("SupportNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly supported, no Fast Linking.
        /// </summary>
        public static string SupportPartly {
            get {
                return ResourceManager.GetString("SupportPartly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SupportUnknown {
            get {
                return ResourceManager.GetString("SupportUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the options at default values unless you know what you&apos;re doing..
        /// </summary>
        public static string TipsNote {
            get {
                return ResourceManager.GetString("TipsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gillian&apos;s GTA IV Setup Utility.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall DXVK.
        /// </summary>
        public static string UninstallDxvk {
            get {
                return ResourceManager.GetString("UninstallDxvk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3GB.
        /// </summary>
        public static string VidMemLimit3GB {
            get {
                return ResourceManager.GetString("VidMemLimit3GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4GB.
        /// </summary>
        public static string VidMemLimit4GB {
            get {
                return ResourceManager.GetString("VidMemLimit4GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The in-game VSync implementation produces framepacing issues. DXVK&apos;s VSync implementation should be preferred.\n\nIt&apos;s recommended to keep this on and in-game&apos;s implementation off..
        /// </summary>
        public static string VSyncTipDescription {
            get {
                return ResourceManager.GetString("VSyncTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding VSync.
        /// </summary>
        public static string VSyncTipTitle {
            get {
                return ResourceManager.GetString("VSyncTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Gillian&apos;s GTA IV Setup Utility!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which DXVK version to install?.
        /// </summary>
        public static string WhichDXVKPrompt {
            get {
                return ResourceManager.GetString("WhichDXVKPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your iGPU supports a greater version of DXVK than your GPU - which version do you wish to install?\n\nPress &apos;Yes&apos; to install the version matching your GPU.\n\nPress &apos;No&apos; to install the version matching your iGPU instead..
        /// </summary>
        public static string WhichDXVKPromptDescription {
            get {
                return ResourceManager.GetString("WhichDXVKPromptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option allows to use Borderless Fullscreen instead of Exclusive Fullscreen. Provides better experience and sometimes better performance. It&apos;s recommended to keep this on..
        /// </summary>
        public static string WindowedTipDescription {
            get {
                return ResourceManager.GetString("WindowedTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding Borderless Windowed.
        /// </summary>
        public static string WindowedTipTitle {
            get {
                return ResourceManager.GetString("WindowedTipTitle", resourceCulture);
            }
        }
    }
}
