name: Build
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore GTAIVSetupUtility.csproj -r win-x64
      
    - name: Publish
      run: dotnet publish GTAIVSetupUtility.csproj --configuration Release --output ./publish/ -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=None -p:DebugSymbols=false -p:BuiltInComInteropSupport=true
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: GTAIVSetupUtility-SelfContained-SingleFile-${{ github.sha }}
        path: ./publish/
        retention-days: 90
